name: gnuplot-editor-unofficial
summary: S
description: D
version: '1.5.1'
grade: stable
confinement: strict
base: core22
license: GPL-3.0
icon: snap/gui/gnuplot-editor-unofficial.png

architectures:
  - build-on: [amd64]
  - build-on: [arm64]

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
      - libglib2.0-bin
    stage-packages:
      - libxkbcommon0
      - fonts-ubuntu
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libqt5svg5 # for loading icon themes which are svg
      - libgdk-pixbuf2.0-0
      - locales-all
      - libglib2.0-bin
    override-prime: |
      craftctl default
      glib-compile-schemas usr/share/glib-2.0/schemas

  qt5-gtk-platform:
    plugin: nil
    stage-packages:
      - qt5-gtk-platformtheme

  gnuplot-editor-unofficial:
    plugin: dump
    source-type: git
    source: https://github.com/faveoled/gpedit
    source-commit: 461d203dc80dbe8096dabc97457d82595e006e9a      
    stage-packages:
      - gnuplot
      - gnuplot-qt
      - python3-pyqt5
      - python3-pyqt5.qtsvg
      - python3-pyqt5.qsci
      - python3-pyqt5.qtwebkit
    override-prime: |
      craftctl default
      ln -s usr/bin/gnuplot-qt usr/bin/gnuplot || echo      
    after: [desktop-qt5]

apps:
  gnuplot-editor-unofficial:
    command: bin/desktop-launch $SNAP/gped
    desktop: dist_data/GnuplotEditor.desktop
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin:$PATH
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.10/site-packages:$SNAP/usr/local/lib/python3.10/dist-packages:$SNAP/usr/lib/python3.10/dist-packages:$PYTHONPATH
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
      # Use GTK3 cursor theme, icon theme and open/save file dialogs.
      QT_QPA_PLATFORMTHEME: gtk3
    plugs:
      - x11
      - unity7
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - removable-media

layout:
  /usr/lib/gnuplot:
    bind: $SNAP/usr/lib/gnuplot

plugs:
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
